# Generated by Django 5.0.7 on 2024-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('count', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Product-Images/')),
                ('popularity', models.CharField(max_length=50)),
                ('sale_amount', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=100)),
                ('product_code', models.IntegerField()),
            ],
        ),
    ]
