# Generated by Django 5.0.7 on 2024-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('discount_code', models.IntegerField()),
            ],
        ),
    ]
