# Generated by Django 5.0.7 on 2024-07-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_code',
        ),
    ]
