# Generated by Django 5.0.7 on 2024-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.IntegerField(null=True),
        ),
    ]
