# Generated by Django 5.0.7 on 2024-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_comment_admin_reply_comment_date_comment_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
