# Generated by Django 5.0.7 on 2024-07-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0007_rename_date_comment_datee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datee',
            new_name='date',
        ),
    ]
