# Generated by Django 5.0.7 on 2024-07-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0015_comment_time_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
