# Generated by Django 5.0.7 on 2024-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
